export const data = {
  products: [
    {
      id: '1',
      name: 'Medicina 1',
      image: '',
      price: 120,
      countInStock: 10,
      category: '',
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      id: '2',
      name: 'Medicina 2',
      image: '',
      price: 250,
      countInStock: 0,
      category: '',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '3',
      name: 'Medicina 3',
      image: '',
      price: 25,
      countInStock: 15,
      category: 'Category1',
      numReviews: 14,
      description: 'high quality product',
    },
    {
      id: '4',
      name: 'Medicina 4',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category2',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '5',
      name: 'Medicina 5',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category3',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '6',
      name: 'Medicina 6',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category4',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '7',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '8',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '9',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '10',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '11',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '12',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '13',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '14',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '15',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '16',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '17',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '18',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '19',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '20',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '21',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '22',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '23',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: '24',
      name: 'Medicina 7',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category5',
      numReviews: 10,
      description: 'high quality product',
    },
  ],
}
